backend/.gitignore, backend/app/__init__.py, backend/app/order.py, backend/application.py, backend/requirements.txt
- Basic flask app
- Functional but unfinished endpoint to place orders and send them to appropriate email address.
=> Backend initial

utils/chip-form.py, website/buildspec.yml, website/src/components/OrderCreate.vue, website/src/store/chips.js
- Add all chip types to website
closes issue #34
=> All chip types

.gitignore, website/src/components/Order.vue, website/src/components/OrderCreate.vue, website/src/components/OrderSettings.vue, website/src/components/OrderSuccess.vue, website/src/store/index.js, website/src/store/orders/actions.js, website/src/store/orders/getters.js, website/src/store/orders/mutation.js, website/src/store/routes.js
Still needs some work but this is a good start.
Close #42  Order settings page
Close #18 Create employee list
=> Order settings page

backend/app/order.py
First bit of work on parsing json and writing to csv file. Does not yet work with Will's code.
=> parsing json in post request to construct csv file

backend/app/order.py
delivery date will simply be day of week if date is within the current week. If it is past that point the delivery date will be the day of the week followed by the date in mm/dd format
=> changed date formatting. 

website/src/components/Order.vue, website/src/components/OrderCreate.vue
=> Scroll through all items

backend/app/order.py
=> writing the notes into the csv file being generated

backend/app/write_order_xlsx.py
- some pep8 formating changes (autoformater)
- The ui sometimes sends an empty object in the order. Check item has `type` key before using it [here](https://github.com/williamh890/FairbanksDistributors/blob/bc84e0bba6dc03b54cbf0470243a5dad4b8a1865/backend/app/write_order_xlsx.py#L103-L104).
=> Big order bug fix

backend/app/write_order_xlsx.py, excelParse/chip_form.py, website/src/App.vue, website/src/components/Order.vue, website/src/components/OrderSuccess.vue
built off of big-order-fix, only relavent changes are in chip_form.py and App.vue
=> Category ordering

website/src/store/routes.js
The app is going to start printing. We need to be able to still test. This is a quick fix.
=> Add test store which will be an order that should not be printed

website/src/components/OrderCreate.vue, website/src/components/OrderReview.vue
- Cancel button for item dialog
- Remove detailed item info
- Change color of item amount chip if 0
- Add case total to review screen
=> User feedback updates

website/src/App.vue, website/src/components/Order.vue, website/src/components/OrderCreate.vue, website/src/components/OrderReview.vue, website/src/store/index.js, website/src/store/orders/actions.js, website/src/store/orders/getters.js, website/src/store/orders/mutation.js
- Save category order when sending order items to backend
- Category headers on order create and review screens
- Remove category name from item names
=> Website item categories

website/src/components/OrderCreate.vue, website/src/components/OrderReview.vue
Adds additional clarity on where categories begin/end.
Fixes auto scrolling to work again after previous change broke it.
=> Toolbar dividers

website/src/components/Order.vue, website/src/components/OrderCreate.vue, website/src/components/OrderReview.vue
Review #152 and merge it before reviewing this PR
Have more space for order items on create/review screen by removing some padding.
Add v-dividers in between items on orderCreate for better aesthetic due to removing items details.
=> Remove order padding

website/src/components/OrderCreate.vue, website/src/components/OrderReview.vue
I'm still not sold on that icon for order review screen though. Would you merge into master after reviewing?
=> Rollback based on feedback

email_scripts/windows_scrape_inbox_and_print.py
Change the email script to include the conditional statement that has been used by the warehouse computer to grab only the proper emails.
=> Add conditional

backend/app/order.py
The way that Git represents the change might look weird but it's impressively right... It'll make more sense if you just look at the file though.
=> Refactor: Remove repetition in getting order items

website/.gitignore, website/package-lock.json, website/src/components/MainMenu.vue, website/src/components/Order.vue, website/src/components/OrderNotes.vue, website/src/components/OrderSettings.vue, website/src/store/orders/actions.js, website/src/store/orders/mutation.js
=> Cache in progress orders

backend/app/write_order_xlsx.py
This is being merged to dev branch to test. Hopefully makes the font size not scale to be so small on the page as well as fixes a peeve of mine regarding column splitting.
=> Increase order text size

backend/app/write_order_xlsx.py
strip leading zero, strip leading whitespace, change space to hyphens, sub FZ for 72220, take first 8 characters
=> shorten bread upcs

backend/app/write_order_xlsx.py
Add request of Greg, revert to old version of order sheet.
=> revert_write_order
